"""Add username and password fields to employee table

Revision ID: 0cac94f4c562
Revises: 
Create Date: 2025-07-07 11:00:25.421156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cac94f4c562'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, we need to recreate the table to add NOT NULL columns
    # First, create a new table with the required structure
    op.create_table('employees_new',
        sa.Column('id', sa.String(), primary_key=True),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('first_name', sa.String(), nullable=False),
        sa.Column('last_name', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('position', sa.String(), nullable=True),
        sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='employeestatus'), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    )
    
    # Copy data from old table to new table with default values for new columns
    op.execute("""
        INSERT INTO employees_new 
        (id, email, username, hashed_password, first_name, last_name, phone, position, status, created_at, updated_at, last_active)
        SELECT 
            id, 
            email, 
            'user_' || id as username,
            '$2b$12$defaulthashforexistingusers' as hashed_password,
            first_name, 
            last_name, 
            phone, 
            position, 
            status, 
            created_at, 
            updated_at, 
            last_active
        FROM employees
    """)
    
    # Drop old table
    op.drop_table('employees')
    
    # Rename new table to original name
    op.rename_table('employees_new', 'employees')
    
    # Create indexes
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.drop_column('employees', 'hashed_password')
    op.drop_column('employees', 'username')
    # ### end Alembic commands ### 