"""Add app usage data to time entries

Revision ID: 1748ce391c9f
Revises: 0cac94f4c562
Create Date: 2025-07-07 16:56:28.359873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1748ce391c9f'
down_revision = '0cac94f4c562'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_entries', sa.Column('app_usage_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_entries', 'app_usage_data')
    # ### end Alembic commands ### 