"""Fix employee status enum values

Revision ID: 64e3afa8134a
Revises: 1748ce391c9f
Create Date: 2025-07-07 18:58:35.724356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e3afa8134a'
down_revision = '1748ce391c9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The enum expects lowercase values as defined in the model
    # No changes needed - the data should already be correct
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 